# Generated by Django 3.2.12 on 2024-04-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='foto',
        ),
    ]
