# Generated by Django 3.2.12 on 2024-05-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_remove_veiculo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculo/fotos'),
        ),
    ]
